name = "Cihangir Timur Sefergil"

profile-picture = "GitHub"

bio = "A CS student who loves low level stuff and especially Rust"

github = "CTimurSefergil"

discord = "TimurSefergil#7943"
discord-userid = "1132743049458483331"

twitter = "Sefergil29"

itch-io = "CTimurSefergil"